version: "3.8"

services:
  backend:
    build:
      context: ./smartplagas-backend
    ports:
      - "3001:3001"
    env_file:
      - ./smartplagas-backend/.env
    volumes:
      - ./smartplagas-backend:/app
    restart: always

  bot:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
